import Foundation

enum YouTubeCaptionTrackKind: String, Codable, CaseIterable, Hashable, Sendable {
    case standard
    case asr
    case translated
}

struct YouTubeCaptionTrack: Codable, Identifiable, Hashable, Sendable {
    let id: String
    let languageCode: String
    let languageName: String
    var kind: YouTubeCaptionTrackKind
    var isDefault: Bool
    var sourceLanguageCode: String?
    var url: String?

    init(
        id: String,
        languageCode: String,
        languageName: String,
        kind: YouTubeCaptionTrackKind = .standard,
        isDefault: Bool = false,
        sourceLanguageCode: String? = nil,
        url: String? = nil
    ) {
        self.id = id
        self.languageCode = languageCode
        self.languageName = languageName
        self.kind = kind
        self.isDefault = isDefault
        self.sourceLanguageCode = sourceLanguageCode
        self.url = url
    }

    var isAutoGenerated: Bool {
        kind == .asr
    }

    var displayLabel: String {
        isAutoGenerated ? "\(languageName) (Auto)" : languageName
    }

    var cacheKey: String {
        "\(languageCode)::\(kind.rawValue)::\(id)"
    }
}
